### ISSUE TITLE
XScreensaver deactivation on TV on

### ISSUE THREAD

**Issue by nischi** [nischi/MMM-CECControl#2]
Like @SdeGeata said in the other issue, would be nice to deactivate the xScreensaver on TV on which make totally sense.

https://github.com/nischi/MMM-MotionControl/issues/3

**Comment by SdeGeata** [comment]
That’d be so great i you could get that in! I messed with scripts all day long trying to get a startup script going with PIR motion detection and just couldn’t get it working. Either it ran and shut off the screen saver - then prevented it restarting later or it ran and exited; a once-only solution to deactivating the screensaver. I am just not a programmer yet. I’m grateful for people like you who actually know what their doing.

**Comment by nischi** [comment]
Can you please test it for me?
https://github.com/nischi/MMM-CECControl/tree/1.1

**Comment by SdeGeata** [comment]
Hello again!

Yeah, i'll be thrilled to test that for you - as soon as i get my new camera ribbon cable. The last one snapped a few lines through repeated manipulation. Should be pretty quick. I will keep you posted.

Thanks again!

**Comment by SdeGeata** [comment]
So far, still no ribbon cable - should arrive tomorrow... but i did install the update. I am getting these errors in terminal:

`pm2 log mm
[TAILING] Tailing last 15 lines for [mm] process (change the value with --lines option)
/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm       |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:11:23)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:75:3)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.
`

**Comment by nischi** [comment]
@SdeGeata do you have done a `npm ci`? because new i use an external module

**Comment by SdeGeata** [comment]
@Nischi. Yeah, i did the NPM ci, as per the listed dependencies - though i am not 100% sure it was in the right directory... it took a long time to install. :-/ I called it while in the MM directory. Was i in error?

**Comment by nischi** [comment]
You need to do that in CECControl directory. Error sounds like it do not find something. But i will implement another fix, i will inform you if i have the new Version, maybe you have the same strange thing as i had.

**Comment by SdeGeata** [comment]
It seems that way. Is there a way to view an installation log on that package to see where it was all installed?

**Comment by nischi** [comment]
https://github.com/nischi/MMM-CECControl/tree/1.2

Have implemented a new version with queue
